# config for analysis

# most CPUs to ever use at once
max_cpus: 8

# amplicons sequenced by PacBio
amplicons_Wuhan_Hu_1: data/PacBio_amplicon_Wuhan_Hu_1.gb

# how to parse the amplicon
feature_parse_specs_Wuhan_Hu_1: data/feature_parse_specs_Wuhan_Hu_1.yaml

# do we get the sequencing data from locally on our server versus SRA?
seqdata_source: local

# list of Illumina sequencing runs of barcodes
barcode_runs: data/barcode_runs.csv

# wildtype sequence of mutagenized gene
wildtype_sequence: data/wildtype_sequence.fasta
site_number_offset: 330  # add this to sequential sites to get PDCoV RBD numbering

# pdbs for mapping, analysis
pdb_6m0j: data/6m0j.pdb

# URLs from which we download binding & expression of mutants from prior DMS studies
mut_bind-monomer_expr_url: https://media.githubusercontent.com/media/jbloomlab/SARS-CoV-2-RBD_DMS_Omicron/main/results/final_variant_scores/final_variant_scores.csv
mut_bind-dimer_expr_url: https://media.githubusercontent.com/media/jbloomlab/SARS-CoV-2-RBD_DMS/master/results/single_mut_effects/single_mut_effects.csv

# output directories / files
summary_dir: results/summary
figs_dir: results/figures

#manually compiled pool of barcode-variant lookups:
codon_variant_table: data/bc_variant_lookup_pooled.csv

#downloads of prior data
mut_bind-monomer_expr: results/prior_DMS_data/mutant_ACE2-monomer-binding_expression.csv
mut_bind-dimer_expr: results/prior_DMS_data/mutant_ACE2-dimer-binding_expression.csv


counts_dir: results/counts
variant_counts_file: results/counts/variant_counts.csv.gz

binding_scores_dir: results/binding_scores
deer_Kds_file: results/binding_scores/deer-ACE2_bc_binding.csv
hamster_Kds_file: results/binding_scores/hamster-ACE2_bc_binding.csv
cat_Kds_file: results/binding_scores/cat-ACE2_bc_binding.csv
bat_Kds_file: results/binding_scores/bat-ACE2_bc_binding.csv

final_variant_scores_dir: results/final_variant_scores
final_variant_scores_mut_file: results/final_variant_scores/final_variant_scores.csv

epistatic_shifts_dir: results/epistatic_shifts
JSD_file: results/epistatic_shifts/JSD_by_target.csv

visualization_dir: docs/_includes

# Parameters for processing Illumina barcodes, assuming this structure:
#  [R2 binds] - [upstream] - [barcode] - [downstream] - [R1 binds]
#  This orientation is hard-wired in the barcode parser, but here it is opposite
#  Therefore, supplied the "downstream" sequence as reverse complemented upstream
# Passed to `dms_variants.illuminabarcodeparser.IlluminaBarcodeParser`:
illumina_barcode_parser_params:
  upstream: GGCCGC
  downstream: ''
  minq: 20
  upstream_mismatch: 1
  downstream_mismatch: 0

# Input files for analyses from the data subdirectory
RBD_sites: data/RBD_sites.csv
